tags = ['Abolition',
        'Arts, Entertainment, Literature',
        'Business and Entrepreneurship',
        'Civil and Human Rights',
        'Education',
        'Environment',
        'Government and Politics',
        'Health',
        'LGBTQ',
        'Law',
        'Literature and Journalism',
        'Military',
        'Religion',
        'Science, Technology, Engineering, Math (STEM)',
        'Sports',
        'Suffrage',
        'Other']

tag_choices = [('Abolition', 'Abolition'),
               ('Arts, Entertainment, Literature', 'Arts, Entertainment, Literature'),
               ('Business and Entrepreneurship', 'Business and Entrepreneurship'),
               ('Civil and Human Rights', 'Civil and Human Rights'),
               ('Education', 'Education'),
               ('Environment', 'Environment'),
               ('Government and Politics', 'Government and Politics'),
               ('Health', 'Health'),
               ('LGBTQ', 'LGBTQ'),
               ('Law', 'Law'),
               ('Literature and Journalism', 'Literature and Journalism'),
               ('Military', 'Military'),
               ('Religion', 'Religion'),
               ('Science, Technology, Engineering, Math (STEM)',
                'Science, Technology, Engineering, Math (STEM)'),
               ('Sports', 'Sports'),
               ('Suffrage', 'Suffrage'),
               ('Other', 'Other')]
