tags = ['Abolition',
        'Arts and Entertainment',
        'Business and Entrepreneurship',
        'Civil and Human Rights',
        'Education',
        'Environment',
        'Government and Politics',
        'Health',
        'LGBTQ',
        'Law',
        'Literature and Journalism',
        'Military',
        'Religion',
        'Science, Technology, Engineering and Math (STEM)',
        'Sports',
        'Suffrage',
        'Other']
