YOUTUBE_FULL_URL = "youtube.com/watch?v="
YOUTUBE_FULL_URL_SPLIT = "watch?v="
YOUTUBE_EMBED_URL = "https://www.youtube.com/embed/{}"
YOUTUBE_SHORT_URL = "youtu.be/"
VIMEO_STRING = "vimeo"
VIMEO_URL = "vimeo.com/"
VIMEO_EMBED_URL = "https://player.vimeo.com/video/{}"
