"""Added password hashing

Revision ID: 0e29906d9d4c
Revises: eae09133ab90
Create Date: 2016-07-25 11:16:12.445532

"""

# revision identifiers, used by Alembic.
revision = '0e29906d9d4c'
down_revision = 'eae09133ab90'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.drop_column('users', 'password')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('users', 'password_hash')
    ### end Alembic commands ###
