"""with_enums

Revision ID: 111099650c83
Revises: None
Create Date: 2016-07-22 10:06:19.030493

"""

# revision identifiers, used by Alembic.
revision = '111099650c83'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment_edits', 'type',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)
    op.alter_column('flags', 'type',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('flags', 'type',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('comment_edits', 'type',
               existing_type=sa.VARCHAR(length=6),
               nullable=False)
    ### end Alembic commands ###
