"""utctime

Revision ID: 13af99fa906
Revises: 8a595187b2
Create Date: 2016-07-28 15:25:30.027203

"""

# revision identifiers, used by Alembic.
revision = '13af99fa906'
down_revision = '8a595187b2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
