"""added just_now in Post table

Revision ID: 1459ec15d0
Revises: 4bdb03fd598
Create Date: 2016-07-31 22:04:45.181273

"""

# revision identifiers, used by Alembic.
revision = '1459ec15d0'
down_revision = '4bdb03fd598'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
