"""datetime

Revision ID: 17b768ffe92
Revises: 4b7fbc1ba16
Create Date: 2016-07-27 09:57:07.231262

"""

# revision identifiers, used by Alembic.
revision = '17b768ffe92'
down_revision = '4b7fbc1ba16'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_posts_creation_time', 'posts', ['creation_time'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_creation_time', 'posts')
    ### end Alembic commands ###
