"""blob test

Revision ID: 17ca62d3885e
Revises: c1b964c92b7e
Create Date: 2016-08-09 14:31:09.236843

"""

# revision identifiers, used by Alembic.
revision = '17ca62d3885e'
down_revision = 'c1b964c92b7e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('html_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('html_template', sa.Text(), nullable=True),
    sa.Column('quote', sa.String(length=140), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('theme', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imgaes',
    sa.Column('id', sa.Interval(), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imgaes')
    op.drop_table('html_modules')
    ### end Alembic commands ###
