"""forgery

Revision ID: 21317629b6a
Revises: 17b768ffe92
Create Date: 2016-07-27 14:37:29.232364

"""

# revision identifiers, used by Alembic.
revision = '21317629b6a'
down_revision = '17b768ffe92'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
