"""added confirmed to User

Revision ID: 23e2442346a
Revises: 4eac6585d45
Create Date: 2016-07-30 22:43:51.887967

"""

# revision identifiers, used by Alembic.
revision = '23e2442346a'
down_revision = '4eac6585d45'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
