"""initial migration

Revision ID: 2cdfa5e0b5c5
Revises: None
Create Date: 2016-08-12 10:25:55.604157

"""

# revision identifiers, used by Alembic.
revision = '2cdfa5e0b5c5'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('html_modules')
    op.drop_table('images')
    op.add_column('post_edits', sa.Column('creation_time', sa.DateTime(), nullable=True))
    op.alter_column('post_edits', 'edit_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('posts', sa.Column('edit_time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'edit_time')
    op.alter_column('post_edits', 'edit_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('post_edits', 'creation_time')
    op.create_table('images',
    sa.Column('id', postgresql.INTERVAL(), autoincrement=False, nullable=False),
    sa.Column('image', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='images_pkey')
    )
    op.create_table('html_modules',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('html_template', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quote', sa.VARCHAR(length=140), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('theme', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='html_modules_pkey')
    )
    ### end Alembic commands ###
