"""initial migration

Revision ID: 2f7e48a35458
Revises: 
Create Date: 2017-02-17 11:31:02.266740

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f7e48a35458'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('addressed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poster_first', sa.String(length=30), nullable=True),
    sa.Column('poster_last', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('guid', sa.String(length=64), nullable=False),
    sa.Column('auth_user_type', sa.Enum('Saml2In:NYC Employees', 'LDAP:NYC Employees', 'FacebookSSO', 'MSLiveSSO', 'YahooSSO', 'LinkedInSSO', 'GoogleSSO', 'EDIRSSO', 'AnonymousUser', name='auth_user_type'), nullable=False),
    sa.Column('is_mod', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=False),
    sa.Column('middle_initial', sa.String(length=1), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('email_validated', sa.Boolean(), nullable=False),
    sa.Column('terms_of_use_accepted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activist_first', sa.String(length=30), nullable=False),
    sa.Column('activist_last', sa.String(length=30), nullable=False),
    sa.Column('activist_start', sa.Integer(), nullable=False),
    sa.Column('activist_end', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=5000), nullable=False),
    sa.Column('activist_url', sa.String(length=254), nullable=True),
    sa.Column('image_url', sa.String(length=254), nullable=True),
    sa.Column('video_url', sa.String(length=254), nullable=True),
    sa.Column('poster_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.ForeignKeyConstraint(['poster_id'], ['posters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('content', sa.String(length=254), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('Featured', 'Then', 'Now', 'Event', name='type'), nullable=True),
    sa.Column('title1', sa.String(length=50), nullable=True),
    sa.Column('title2', sa.String(length=50), nullable=True),
    sa.Column('activist_first', sa.String(length=30), nullable=True),
    sa.Column('activist_last', sa.String(length=30), nullable=True),
    sa.Column('content', sa.String(length=500), nullable=True),
    sa.Column('media_url', sa.String(length=254), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('activist_year', sa.String(length=4), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('user_guid', sa.String(length=64), nullable=True),
    sa.Column('type', sa.Enum('Edit Story', 'Delete Story', 'Edit Comment', 'Delete Comment', 'Edit Featured Story', 'Edit Then and Now', 'Edit Event', name='type'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('previous_value', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.ForeignKeyConstraint(['user_guid'], ['users.guid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('Inappropriate Content', 'Incorrect Information', 'Offensive Content', 'Other', name='type'), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('addressed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flags')
    op.drop_table('events')
    op.drop_table('modules')
    op.drop_table('comments')
    op.drop_table('stories')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_table('roles')
    op.drop_table('posters')
    op.drop_table('feedback')
    # ### end Alembic commands ###
