"""added media link

Revision ID: 34d5d14906e6
Revises: 7304c9d7998e
Create Date: 2016-08-17 16:22:37.698085

"""

# revision identifiers, used by Alembic.
revision = '34d5d14906e6'
down_revision = '7304c9d7998e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('media_link', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'media_link')
    ### end Alembic commands ###
