"""added password table

Revision ID: 36cb11abc3cf
Revises: facfc681da91
Create Date: 2016-08-17 10:36:49.314006

"""

# revision identifiers, used by Alembic.
revision = '36cb11abc3cf'
down_revision = 'facfc681da91'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passwords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('p1', sa.String(length=128), nullable=True),
    sa.Column('p2', sa.String(length=128), nullable=True),
    sa.Column('p3', sa.String(length=128), nullable=True),
    sa.Column('p4', sa.String(length=128), nullable=True),
    sa.Column('p5', sa.String(length=128), nullable=True),
    sa.Column('last_changed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('login_attempts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('old_passwords', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'passwords', ['old_passwords'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'old_passwords')
    op.drop_column('users', 'login_attempts')
    op.drop_table('passwords')
    ### end Alembic commands ###
