"""added to Post, created Poster and Event

Revision ID: 3abc91789915
Revises: None
Create Date: 2016-08-08 12:18:27.427270

"""

# revision identifiers, used by Alembic.
revision = '3abc91789915'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=50), nullable=True),
    sa.Column('is_subscribed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('posts', sa.Column('activist_end', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('activist_first', sa.String(length=30), nullable=True))
    op.add_column('posts', sa.Column('activist_last', sa.String(length=30), nullable=True))
    op.add_column('posts', sa.Column('activist_start', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('poster_first', sa.String(length=30), nullable=True))
    op.add_column('posts', sa.Column('poster_last', sa.String(length=30), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'poster_last')
    op.drop_column('posts', 'poster_first')
    op.drop_column('posts', 'activist_start')
    op.drop_column('posts', 'activist_last')
    op.drop_column('posts', 'activist_first')
    op.drop_column('posts', 'activist_end')
    op.drop_table('posters')
    op.drop_table('events')
    ### end Alembic commands ###
