"""Added password reset functions to User

Revision ID: 3caa42ad56d
Revises: 23e2442346a
Create Date: 2016-07-30 23:21:03.284784

"""

# revision identifiers, used by Alembic.
revision = '3caa42ad56d'
down_revision = '23e2442346a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
