"""Add rank column in FeaturedStories

Revision ID: 40148387e653
Revises: 3fc349f30939
Create Date: 2018-03-08 18:42:42.945381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40148387e653'
down_revision = '3fc349f30939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('featuredstories', sa.Column('rank', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('featuredstories', 'rank')
    # ### end Alembic commands ###
