"""initial migration

Revision ID: 40a4645488f0
Revises: None
Create Date: 2016-08-16 11:06:55.330014

"""

# revision identifiers, used by Alembic.
revision = '40a4645488f0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author_first', sa.String(length=30), nullable=True))
    op.add_column('posts', sa.Column('author_last', sa.String(length=30), nullable=True))
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
    op.drop_column('posts', 'author_last')
    op.drop_column('posts', 'author_first')
    ### end Alembic commands ###
