"""removed role enum in User table

Revision ID: 40f6f290182a
Revises: eadaa0fc7c09
Create Date: 2016-08-02 11:43:39.817684

"""

# revision identifiers, used by Alembic.
revision = '40f6f290182a'
down_revision = 'eadaa0fc7c09'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('Administrator', 'Agency User', name='user_roles'), autoincrement=False, nullable=False))
    ### end Alembic commands ###
