"""added content_html in Post table

Revision ID: 4759717e098
Revises: 21317629b6a
Create Date: 2016-07-28 01:13:52.667327

"""

# revision identifiers, used by Alembic.
revision = '4759717e098'
down_revision = '21317629b6a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('content_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'content_html')
    ### end Alembic commands ###
