"""Working directory minus share

Revision ID: 4b97380fb9a2
Revises: 1e98d3ac2bdd
Create Date: 2016-08-01 10:43:33.301221

"""

# revision identifiers, used by Alembic.
revision = '4b97380fb9a2'
down_revision = '1e98d3ac2bdd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
