"""added title to PostEdit

Revision ID: 4b9f01c4cba4
Revises: 40f6f290182a
Create Date: 2016-08-04 21:12:45.926051

"""

# revision identifiers, used by Alembic.
revision = '4b9f01c4cba4'
down_revision = '40f6f290182a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_edits', sa.Column('title', sa.String(length=140), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_edits', 'title')
    ### end Alembic commands ###
