"""changed reason length in flag table

Revision ID: 4bdb03fd598
Revises: 3caa42ad56d
Create Date: 2016-07-31 00:57:02.437357

"""

# revision identifiers, used by Alembic.
revision = '4bdb03fd598'
down_revision = '3caa42ad56d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
