"""changed User/Role comments

Revision ID: 4eac6585d45
Revises: 13af99fa906
Create Date: 2016-07-30 21:25:15.931629

"""

# revision identifiers, used by Alembic.
revision = '4eac6585d45'
down_revision = '13af99fa906'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
