"""empty message

Revision ID: 53651ae20b91
Revises: 8e9225f18301
Create Date: 2016-08-12 11:35:56.882940

"""

# revision identifiers, used by Alembic.
revision = '53651ae20b91'
down_revision = '8e9225f18301'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flags', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'flags', 'comments', ['comment_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flags', type_='foreignkey')
    op.drop_column('flags', 'comment_id')
    ### end Alembic commands ###
