"""added feedback table

Revision ID: 53ccaa363d86
Revises: d2dc19fe9d11
Create Date: 2016-07-20 09:56:59.658571

"""

# revision identifiers, used by Alembic.
revision = '53ccaa363d86'
down_revision = 'd2dc19fe9d11'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    ### end Alembic commands ###
