"""empty message

Revision ID: 57b6f9ab2b0c
Revises: 114411e2862a
Create Date: 2016-08-16 11:25:25.765565

"""

# revision identifiers, used by Alembic.
revision = '57b6f9ab2b0c'
down_revision = '114411e2862a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('activist_link', sa.String(length=30), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'activist_link')
    ### end Alembic commands ###
