"""Updated character limits

Revision ID: 593629cfd6cd
Revises: f32a9ba548dc
Create Date: 2023-08-02 12:27:43.011305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '593629cfd6cd'
down_revision = 'f32a9ba548dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "first_name",
        existing_type=sa.VARCHAR(length=128),
        type_=sa.VARCHAR(length=600),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "last_name",
        existing_type=sa.VARCHAR(length=128),
        type_=sa.VARCHAR(length=600),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "email",
        existing_type=sa.VARCHAR(length=254),
        type_=sa.VARCHAR(length=1024),
        existing_nullable=True,
    )
    op.alter_column(
        "stories",
        "activist_first",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.VARCHAR(length=300),
        existing_nullable=True,
    )
    op.alter_column(
        "stories",
        "activist_last",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.VARCHAR(length=300),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "first_name",
        existing_type=sa.VARCHAR(length=300),
        type_=sa.VARCHAR(length=128),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "last_name",
        existing_type=sa.VARCHAR(length=600),
        type_=sa.VARCHAR(length=128),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "email",
        existing_type=sa.VARCHAR(length=1024),
        type_=sa.VARCHAR(length=254),
        existing_nullable=True,
    )
    op.alter_column(
        "stories",
        "activist_first",
        existing_type=sa.VARCHAR(length=300),
        type_=sa.VARCHAR(length=64),
        existing_nullable=True,
    )
    op.alter_column(
        "stories",
        "activist_last",
        existing_type=sa.VARCHAR(length=300),
        type_=sa.VARCHAR(length=64),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
