"""Add image_pc

Revision ID: 62959ade4b21
Revises: f32a9ba548dc
Create Date: 2019-10-03 11:07:41.899177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62959ade4b21'
down_revision = 'f32a9ba548dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('image_pc', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'image_pc')
    # ### end Alembic commands ###
