"""empty message

Revision ID: 63bab7e9759e
Revises: None
Create Date: 2016-08-12 14:54:54.340419

"""

# revision identifiers, used by Alembic.
revision = '63bab7e9759e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flags', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'flags', 'comments', ['comment_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flags', type_='foreignkey')
    op.drop_column('flags', 'comment_id')
    ### end Alembic commands ###
