"""Version 1

Revision ID: 67f4bc260180
Revises: 53ccaa363d86
Create Date: 2016-07-20 11:14:55.456614

"""

# revision identifiers, used by Alembic.
revision = '67f4bc260180'
down_revision = '53ccaa363d86'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedback', 'title',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.drop_index('ix_users_email', table_name='users')
    op.create_unique_constraint(None, 'users', ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.alter_column('feedback', 'title',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    ### end Alembic commands ###
