"""added image and video link to stories table

Revision ID: 7304c9d7998e
Revises: None
Create Date: 2016-08-17 15:16:37.305815

"""

# revision identifiers, used by Alembic.
revision = '7304c9d7998e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('image_link', sa.Text(), nullable=True))
    op.add_column('stories', sa.Column('video_link', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'video_link')
    op.drop_column('stories', 'image_link')
    ### end Alembic commands ###
