"""inital migration

Revision ID: 76f2e2849459
Revises: None
Create Date: 2016-08-08 16:40:29.951519

"""

# revision identifiers, used by Alembic.
revision = '76f2e2849459'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_edits', sa.Column('title', sa.String(length=140), nullable=True))
    op.add_column('post_edits', sa.Column('version', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('activist_end', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('activist_first', sa.String(length=30), nullable=True))
    op.add_column('posts', sa.Column('activist_last', sa.String(length=30), nullable=True))
    op.add_column('posts', sa.Column('activist_start', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('poster_first', sa.String(length=30), nullable=True))
    op.add_column('posts', sa.Column('poster_last', sa.String(length=30), nullable=True))
    op.add_column('posts', sa.Column('version', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('is_subscribed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('site', sa.String(length=50), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('users', 'site')
    op.drop_column('users', 'is_subscribed')
    op.drop_column('posts', 'version')
    op.drop_column('posts', 'poster_last')
    op.drop_column('posts', 'poster_first')
    op.drop_column('posts', 'activist_start')
    op.drop_column('posts', 'activist_last')
    op.drop_column('posts', 'activist_first')
    op.drop_column('posts', 'activist_end')
    op.drop_column('post_edits', 'version')
    op.drop_column('post_edits', 'title')
    ### end Alembic commands ###
