"""Added azure blob name

Revision ID: 87c203341f50
Revises: 593629cfd6cd
Create Date: 2024-07-29 15:28:12.464135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87c203341f50'
down_revision = '593629cfd6cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_blob_name', sa.Text(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=600),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=600),
               type_=sa.String(length=300),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('last_name',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=600),
               existing_nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=600),
               existing_nullable=True)

    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_column('image_blob_name')

    # ### end Alembic commands ###
