"""changed feedback values

Revision ID: 8a595187b2
Revises: 4759717e098
Create Date: 2016-07-28 15:17:38.957022

"""

# revision identifiers, used by Alembic.
revision = '8a595187b2'
down_revision = '4759717e098'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
