"""initial migration

Revision ID: 8e9225f18301
Revises: None
Create Date: 2016-08-11 15:57:18.182489

"""

# revision identifiers, used by Alembic.
revision = '8e9225f18301'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_edits', sa.Column('creation_time', sa.DateTime(), nullable=True))
    op.alter_column('post_edits', 'edit_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('posts', sa.Column('edit_time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'edit_time')
    op.alter_column('post_edits', 'edit_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('post_edits', 'creation_time')
    ### end Alembic commands ###
