"""added version to Post and PostEdit

Revision ID: 8f5389a952dd
Revises: e2b1febd5cb3
Create Date: 2016-08-05 14:16:07.103489

"""

# revision identifiers, used by Alembic.
revision = '8f5389a952dd'
down_revision = 'e2b1febd5cb3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_edits', sa.Column('version', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('version', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'version')
    op.drop_column('post_edits', 'version')
    ### end Alembic commands ###
