"""changed max char

Revision ID: a8159781ce5e
Revises: f32a9ba548dc
Create Date: 2018-08-01 16:31:58.333812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8159781ce5e'
down_revision = 'f32a9ba548dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('featured_stories', 'description',
               existing_type=sa.VARCHAR(length=395),
               nullable=False)
    op.alter_column('featured_stories', 'title',
               existing_type=sa.VARCHAR(length=90),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('featured_stories', 'title',
               existing_type=sa.VARCHAR(length=90),
               nullable=True)
    op.alter_column('featured_stories', 'description',
               existing_type=sa.VARCHAR(length=395),
               nullable=True)
    # ### end Alembic commands ###
