"""initial migration

Revision ID: bc52a2d5b9ba
Revises: None
Create Date: 2016-08-16 10:45:16.074416

"""

# revision identifiers, used by Alembic.
revision = 'bc52a2d5b9ba'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('activist_end_date', sa.Integer(), nullable=False))
    op.add_column('posts', sa.Column('activist_first_name', sa.String(length=30), nullable=True))
    op.add_column('posts', sa.Column('activist_last_name', sa.String(length=30), nullable=True))
    op.add_column('posts', sa.Column('activist_start_date', sa.Integer(), nullable=False))
    op.add_column('posts', sa.Column('author_email', sa.String(length=30), nullable=True))
    op.add_column('posts', sa.Column('author_first_name', sa.String(length=30), nullable=True))
    op.add_column('posts', sa.Column('author_last_name', sa.String(length=30), nullable=True))
    op.add_column('posts', sa.Column('author_website', sa.String(length=30), nullable=True))
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
    op.drop_column('posts', 'poster_last')
    op.drop_column('posts', 'activist_end')
    op.drop_column('posts', 'activist_first')
    op.drop_column('posts', 'poster_first')
    op.drop_column('posts', 'activist_start')
    op.drop_column('posts', 'activist_last')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('activist_last', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('activist_start', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('poster_first', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('activist_first', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('activist_end', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('poster_last', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
    op.drop_column('posts', 'author_website')
    op.drop_column('posts', 'author_last_name')
    op.drop_column('posts', 'author_first_name')
    op.drop_column('posts', 'author_email')
    op.drop_column('posts', 'activist_start_date')
    op.drop_column('posts', 'activist_last_name')
    op.drop_column('posts', 'activist_first_name')
    op.drop_column('posts', 'activist_end_date')
    ### end Alembic commands ###
