"""added title in featured_stories

Revision ID: c25818d790d1
Revises: f32a9ba548dc
Create Date: 2018-07-20 15:06:25.031560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c25818d790d1'
down_revision = 'f32a9ba548dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('featured_stories', sa.Column('title', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('featured_stories', 'title')
    # ### end Alembic commands ###
