"""Add subscription column in Users table

Revision ID: c7ff8db37708
Revises: 40148387e653
Create Date: 2018-03-08 22:14:26.538220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7ff8db37708'
down_revision = '40148387e653'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription')
    # ### end Alembic commands ###
