"""First Real Version

Revision ID: d2dc19fe9d11
Revises: 596094b0b724
Create Date: 2016-07-20 09:36:04.939190

"""

# revision identifiers, used by Alembic.
revision = 'd2dc19fe9d11'
down_revision = '596094b0b724'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    op.alter_column('comments', 'time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('post_edits', 'time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post_edits', 'time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('comments', 'time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='roles_pkey'),
    sa.UniqueConstraint('name', name='roles_name_key')
    )
    ### end Alembic commands ###
