"""ready for merge

Revision ID: d44c0ac5f98d
Revises: 3abc91789915
Create Date: 2016-08-08 13:46:30.336147

"""

# revision identifiers, used by Alembic.
revision = 'd44c0ac5f98d'
down_revision = '3abc91789915'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posters')
    op.add_column('post_edits', sa.Column('version', sa.Integer(), nullable=True))
    op.alter_column('post_edits', 'title',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
    op.add_column('posts', sa.Column('version', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('is_subscribed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('site', sa.String(length=50), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('users', 'site')
    op.drop_column('users', 'is_subscribed')
    op.drop_column('posts', 'version')
    op.alter_column('post_edits', 'title',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
    op.drop_column('post_edits', 'version')
    op.create_table('posters',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_subscribed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='posters_pkey')
    )
    ### end Alembic commands ###
