"""fixed images spelling

Revision ID: dc597ad6f62e
Revises: 17ca62d3885e
Create Date: 2016-08-09 14:32:06.460636

"""

# revision identifiers, used by Alembic.
revision = 'dc597ad6f62e'
down_revision = '17ca62d3885e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Interval(), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('imgaes')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imgaes',
    sa.Column('id', postgresql.INTERVAL(), autoincrement=False, nullable=False),
    sa.Column('image', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='imgaes_pkey')
    )
    op.drop_table('images')
    ### end Alembic commands ###
