"""empty message

Revision ID: e051755ed574
Revises: 57b6f9ab2b0c
Create Date: 2016-08-16 11:27:38.166255

"""

# revision identifiers, used by Alembic.
revision = 'e051755ed574'
down_revision = '57b6f9ab2b0c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    ### end Alembic commands ###
