"""empty message

Revision ID: f4480b04ad61
Revises: 266841845439
Create Date: 2016-08-15 17:25:01.479978

"""

# revision identifiers, used by Alembic.
revision = 'f4480b04ad61'
down_revision = '266841845439'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
    ### end Alembic commands ###
