"""changed quote to description

Revision ID: f8a0adc44733
Revises: c25818d790d1
Create Date: 2018-07-23 16:27:34.119648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8a0adc44733'
down_revision = 'c25818d790d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('featured_stories', sa.Column('description', sa.String(length=445), nullable=True))
    op.drop_column('featured_stories', 'quote')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('featured_stories', sa.Column('quote', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('featured_stories', 'description')
    # ### end Alembic commands ###
