"""PreCodeReview

Revision ID: fd2c6f7321bf
Revises: 67f4bc260180
Create Date: 2016-07-20 11:19:49.233601

"""

# revision identifiers, used by Alembic.
revision = 'fd2c6f7321bf'
down_revision = '67f4bc260180'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedback', 'reason',
               existing_type=sa.TEXT(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedback', 'reason',
               existing_type=sa.TEXT(),
               nullable=True)
    ### end Alembic commands ###
